### ISSUE TITLE
Nextjs NetlifyCMS blog starter template broken

### ISSUE THREAD

**Issue by zackhitch** [wutali/nextjs-netlify-blog#35]
I attempted to use the deploy with netlify button but the starter never populated the repo with any code. https://app.netlify.com/start/deploy?repository=https://github.com/wutali/nextjs-netlify-blog-template&stack=cms

Seems as if the template is broken.

**Comment by falcon-Z** [comment]
I have the same issue,  How did u solve it @zackhitch
